#!/usr/bin/env bash

# this script with patch the given pkg

readonly PKGLIST="$HOME/aur-pkgs-list"
readonly PKGDIR="$HOME/aur-src"
readonly PATCHDIR="$HOME/aur-src-patches"

if [ ! -f "$PKGLIST" ]; then
	echo "Can't find pkg list, create ${CONF} first before running!" >&2
	exit 1
else
	# make sure pkg source dir exists
	mkdir -p "$PKGDIR"

	tmp=$(mktemp -d)
	trap 'rm -rf $tmp' EXIT

	echo -n "Determining AUR dependencies... "
	while read -r pkg; do
		aur depends -b "$pkg" >> "$tmp/depends"
	done < "$PKGLIST"
	echo "done"
	
	sort -u "$tmp/depends" > "$tmp/pkglist"

	pushd "$PKGDIR"
	echo "Fetching packages and their AUR dependencies... "
	# we want to always reset (so that patch apply cleanly)
	find . -mindepth 1 -maxdepth 1 -type d -exec git -C {} reset -q --hard master \;
	xargs -a "$tmp/pkglist" -n1 -P4 aur fetch -g
	popd

	echo "Checking for patchs... "
	while read -r pkg; do
		if [ -d "${PATCHDIR}/${pkg}" ]; then
			echo "   found, patching $pkg"
			find "${PATCHDIR}/${pkg}" -iname '*.patch' -exec patch -d "$PKGDIR/$pkg" -p1 -i {} \;
		fi
	done < "$PKGLIST"
fi
